### ISSUE TITLE
Save backup naming.

### ISSUE THREAD

**Issue by maciak** [thomasnet-mc/EdiZon#3]
Hi,
I've noticed that saves are backed up inlt by title id. Could you also please include real game name for easy management on PC?

**Comment by thomasnet-mc** [comment]
This may pose some problems with UTF-8 characters in Japanese game names, and that can lead up to too much characters in file path. Sorry, but you'll have to resort to seeing the title ID from the editor page/online to get your saves, but if you have another solution please tell us!

**Comment by Favna** [comment]
The title of the issue seems to conflict with the content. The content talks about the name of the path, but the title seems to infer the fact that EdiZon currently backups with datetime strings as opposed to user input names such as `backup` or `restore` (a feature that CheckPoint does have mind you). 

@maciak should start by clarifying which of these 2 he meant with the topic. I think the latter should be totally feasible *because* CheckPoint also allows this.

**Comment by thomasnet-mc** [comment]
It doesn't have backup name putting yet because we're waiting for real software keyboard implementation.

**Comment by WerWolv98** [comment]
I made a project for this a while ago. Backup naming is definitely something we want but as @thomasnet-mc said, we don't have a software keyboard implementation. And doing it like Checkpoint is IMO a really hacky and time consuming alternative. So until we have a working software keyboard all backups will be saved as date_time.

**Comment by maciak** [comment]
@Favna I dont know how to clarify more ;p As in my first post I would prefer that games saves are stored with more friendly names like checkpoint does that. First there is title id and real name of the game and inside are backups that you can name. Here it's only title id and inside are backyps with date and time. Hard to find a game save if toy are not familiar with title id of a game.

**Comment by WerWolv98** [comment]
The main problem is, if anybody uses a game with unicode characters in it (Could be Japanese character but also a ™ will be enough to make EdiZon not backup/restore your game). We had that problem already when we included the account name in the backup because his name was Japanese. In the future there will be a way to name the backups at least so that way you can identify them easier. I'd just like to stick to standard ASCII strings because it makes handling backups a lot easier. I hate having unicode characters inside file paths. They only cause issues

**Comment by maciak** [comment]
Hi,
In checkpoint in case it cannot add game name id adds title id again ;p So eitherway it works preatty good.

**Comment by WerWolv98** [comment]
That's one option but personally I think this is a horrible mess then. Some games will have names, some don't. I rather want it to be consistent than it being different for different games.
